version: '3.8'
services:
  httpd:
    # Apache on http://localhost serves from www and FastCGI proxies .php files to php-fpm:9000
    build: ./docker/httpd-2.4
    ports:
      - "81:80"
    volumes:
      - "./www/html:/var/www/html"
      - "./www/lib:/var/www/lib"
      - "./test/www/html/config.php:/var/www/html/config.php"
      - "./test/www/lib/config.php:/var/www/lib/config.php"
    depends_on:
      - php-fpm
    networks:
      - app-network
    profiles:
      - serve

  php-fpm:
    # Exposes the php-fpm FastCGI process on port 9000 for Apache
    # Can access mariadb
    build: ./docker/php-fpm-8.2
    volumes:
      - "./www/html:/var/www/html"
      - "./www/lib:/var/www/lib"
      - "./test/www/html/config.php:/var/www/html/config.php"
      - "./test/www/lib/config.php:/var/www/lib/config.php"
    env_file:
      - ./env/mariadb.env
    depends_on:
      - mariadb
    networks:
      - app-network
    profiles:
      - serve

  mariadb:
    image: mariadb:10.8.3
    ports:
      - "3306:3306"
    env_file:
      - ./env/mariadb.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    profiles:
      - serve

  phpmyadmin:
    # Runs its own version of Apache exposed on http://localhost:81
    image: phpmyadmin:5.2.1
    links:
      - mariadb
    ports:
      - "82:80"
    environment:
      PMA_HOST: mariadb
    env_file:
      - ./env/mariadb.env
    networks:
      - app-network
    profiles:
      - debug

  test:
    build: ./docker/test
    volumes:
      - ./test:/test
      - ./screenshots:/tmp/screenshots
    networks:
      - app-network
    profiles:
      - test

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
