version: '3.8'
services:
  httpd:
    # Apache on http://localhost serves from www
    build: ./docker/httpd-2.4
    ports:
      - "81:80"
    volumes:
      - "./bin/user.sh:/usr/bin/user.sh"
      - "./bin/wait-for-mariadb.sh:/usr/bin/wait-for-mariadb.sh"
      - "./www/html:/var/www/html"
      - "./www/lib:/var/www/lib"
      - "./www/include:/var/www/include"
    env_file:
      - ./env/mariadb.env
    networks:
      - app-network
    profiles:
      - serve
    depends_on:
      - mariadb
    command: ["/usr/bin/wait-for-mariadb.sh", "mariadb", "httpd-foreground"]

  mariadb:
    image: mariadb:10.8.3
    ports:
      - "3306:3306"
    env_file:
      - ./env/mariadb.env
    volumes:
      - db_data:/var/lib/mysql
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - app-network
    profiles:
      - serve

  phpmyadmin:
    # Runs its own version of Apache exposed on http://localhost:81
    image: phpmyadmin:5.2.1
    links:
      - mariadb
    ports:
      - "82:80"
    environment:
      PMA_HOST: mariadb
    env_file:
      - ./env/mariadb.env
    networks:
      - app-network
    profiles:
      - debug

  test:
    build: ./docker/test
    volumes:
      - ./test:/test
      - ./screenshots:/tmp/screenshots
    networks:
      - app-network
    profiles:
      - test

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
